/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#define BV(n) (1 << (n))

void led_init(void);
void led_run_lr(void);
void led_run_rl(void);
void DelayMs(uint32_t ms);

int main(void)
{
    led_init();

    while (1)
    {
        led_run_lr();
        led_run_rl();
    }
}


void led_init(void)
{
    RCC->AHB1ENR |= BV(3);

    GPIOD->MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));
    GPIOD->MODER |=  (BV(24) | BV(26) | BV(28) | BV(30));

    GPIOD->OTYPER &= ~(BV(12) | BV(13) | BV(14) | BV(15));

    GPIOD->OSPEEDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) |
                        BV(28) | BV(29) | BV(30) | BV(31));

    GPIOD->PUPDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) |
                      BV(28) | BV(29) | BV(30) | BV(31));
}

void led_run_lr(void)
{
    uint8_t pin;

    for (pin = 12; pin <= 15; pin++)
    {
        GPIOD->ODR &= ~(BV(12) | BV(13) | BV(14) | BV(15));

        GPIOD->ODR |= BV(pin);

        DelayMs(500);
    }
}

void led_run_rl(void)
{
    int8_t pin;

    for (pin = 15; pin >= 12; pin--)
    {

        GPIOD->ODR &= ~(BV(12) | BV(13) | BV(14) | BV(15));

        GPIOD->ODR |= BV(pin);

        DelayMs(500);
    }
}

