/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "ext_intr.h"

/* Flag set by ISR */
extern volatile int ext_flag;

/* LED state variable
 * 0 = LED OFF
 * 1 = LED ON
 */
static uint8_t led_state = 0;

int main(void)
{
    led_init();
    extint_init();

    while (1)
    {
        /* Check if button interrupt occurred */
        if (ext_flag == 1)
        {
            if (led_state == 0)
            {
                led_on(12);
                led_state = 1;   // Update state to ON
            }
            else
            {
                led_off(12);
                led_state = 0;   // Update state to OFF
            }

            /* Clear software flag */
            ext_flag = 0;
        }
    }
}




