/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "ext_intr.h"

/*
 * ext_flag is declared as extern here.
 * It is defined in ext_intr.c and modified inside ISR.
 */
extern volatile int ext_flag;

int main(void)
{
    led_init();
    extint_init();

    while (1)
    {
        /* Check if interrupt flag is set */
        if (ext_flag == 1)
        {
            /* LED operation is done in main, NOT in ISR */
            led_toggle(12);

            /* Clear flag after handling */
            ext_flag = 0;
        }
    }
}









